version: "3.9"
services:
  authentication-microservice:
    build: .
    image: authentication-microservice
    container_name: microservice_authentication
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - ENVIRONMENT=development
      - GRPC_PORT=5000
      - REDIS_HOST=redis_server
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - REDIS_DB=0
      - POSTGRES_HOST=postgres_server
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - JWT_SECRET=secret
      - JWT_EXPIRATION=1h
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
  postgres:
    image: postgres:latest
    container_name: postgres_server
    ports:
      - "49153:5432"
    hostname: postgres_server
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=postgres