authentication:
  environment: development
  port: 5000
  dependencies:
    - postgres:
        host: postgres
        port: 5432
        dbname: authentication
        user: postgres
        password: postgres
    - redis:
        host: redis
        port: 6379
        dbname: 0
        user: redis
        password: redis