gateway:
  environment: development
  listen:
    host: localhost
    port: 8080
  services:
    - name: authentication
      host: http://localhost:5000
    - name: session
      host: http://localhost:5001
    - name: setting
      host: http://localhost:5002